name: prjna605983
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - bwa=0.7.17
  - samtools=1.19
  - sra-tools=3.0.10          # fasterq-dump
  - mafft=7.520
  - iqtree=2.3.5
  - biopython=1.83
  - matplotlib=3.8
  - numpy=1.26
  - pip
  - pip:
    - ncbi-datasets-cli
